framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: 'contact@thefunkylagosorchestra.com'
        headers:
            From: 'contact@thefunkylagosorchestra.com'
when@dev:
    framework:
        mailer:
            dsn: 'smtp://127.0.0.1:1025'
